name: First Wrorkflow

on: workflow_dispatch

jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting 
        run : |
            echo "Hello World"
            echo "Hello Mimoto"
            echo "Hello Non-Mimoto"
      - name: print goodbye
        run: echo "Done - bye!"
        
        
