# (Must) Workflow name
name: First Wrorkflow

# (Must) Define trigger
on: workflow_dispatch

# jobs
jobs: 
  # First Job
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting 
        run : |
            echo "Hello World"
            echo "Hello Mimoto"
            echo "Hello Non-Mimoto"
      - name: print goodbye
        run: echo "Done - bye!"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: print stuff
        run: echo "Here is stuff printed."
        
        
