# (Must) Workflow name
name: First Wrorkflow

on: 
  push:
    branches:
      - 'main'

  workflow_dispatch:  # This allows to manually trigger the workflow

# jobs
jobs: 
  # First Job
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        with:
          clean: true         # Execute `git clean -ffdx && git reset --hard HEAD` before fetching.
          fetch-depth: 1      # Number of commits to fetch.
          show-progress: true # Show progress status output when fetching.
          submodules: true    # Ensure submodules are checked out and updated.
          token: ${{ secrets.GITHUB_TOKEN }}  # GitHub-provided token for authentication (temporary).

      - name: Cache the Repository
        id: cache-repo
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-repo-${{ github.sha }}

      - name: Debug Cache Output
        run: |
          echo "Cache hit status: ${{ steps.cache-repo.outputs.cache-hit }}"

      # Step 1: Create a sample artifact file
      - name: Create Artifact File
        run: |
          echo "This is a sample artifact file." > sample_artifact.txt

      # Step 2: Upload the artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-artifact
          path: sample_artifact.txt

      # Step 3: Display message after uploading
      - name: Confirm Artifact Upload
        run: echo "Artifact 'sample-artifact' has been uploaded successfully."
        
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: print stuff
        run: echo "Here is stuff printed."

      - name: Restore the Repository Cache
        id: restore-cache-repo
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-repo-${{ github.sha }}

      - name: Verify Cache Status
        run: |
          if [ "${{ steps.restore-repo.outputs.cache-hit }}" != "true" ]; then
            echo "Cache miss! Repo was not restored."
          else
            echo "Cache hit! Repo was restored successfully."
          fi

      - name: Show Current Directory Path and Content
        run: pwd; ls -ah

  download-and-use:
    runs-on: ubuntu-latest
    needs: build-and-upload

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Download the artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: sample-artifact
          path: ./downloaded_artifacts

      # Step 3: Verify and use the artifact
      - name: Verify Artifact
        run: |
          cat ./downloaded_artifacts/sample_artifact.txt
