
name: Second Workflow
on: 
  push:
    branches:
      - 'main'

  workflow_dispatch:  # This allows to manually trigger the workflow
  
jobs:

  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello There!"
          echo "GuitHub Action Varibale Name "USER_NAME" = ${{vars.agent_ubuntu.variables.USER_NAME}}"
        
  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: install FlatBuffer Compiler
        uses: insightsengineering/pip-action@v2
        with:
          packages: |
            flatbuffers
            pycryptotools

      #- name: Install tree tool
      #  run: |
      #    apt update -y
      #    atp install tree
